<?php

/* * *************************************************************
 * Extension Manager/Repository config file for ext: "openemm"
 *
 * Auto generated by Extension Builder 2015-02-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 * ************************************************************* */

$EM_CONF[$_EXTKEY] = array(
    'title' => 'OpenEMM',
    'description' => 'OpenEMM Newsletter',
    'category' => 'module',
    'author' => 'Markus Pircher',
    'author_email' => 'technik@idealit.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.2',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2',
            'static_info_tables' => ''
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
